[general]
    BorderColor = "#98971a"
    ActiveButtonColor = "#b16286"
    ButtonColor = "#928374"


[[metrics]]
    name = "Got up"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "time"

[[metrics]]
   name = "Went to bed"
    color1 = "#83a598"
   color2 = "#abb31b"
   rule = "time"

[[metrics]]
    name = "Mood"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int10"

[[metrics]]
    name = "Pomos"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int"

[[metrics]]
    name = "Drank water"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int"

# [[metrics]]
#     name = "testlol"
#     color1 = "#282828"
#     color2 = "#395949"
#     rule = "int"
