[general]
    BorderColor = "#98971a"
    ActiveButtonColor = "#b16286"
    ButtonColor = "#928374"

[[metrics]]
   name = "Woke"
   color1 = "#83a598"
   color2 = "#abb31b"
   rule = "time"

[[metrics]]
   name = "Slept"
    color1 = "#83a598"
   color2 = "#abb31b"
   rule = "time"

[[metrics]]
    name = "Mood"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int10"

[[metrics]]
    name = "Studied"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int"

[[metrics]]
    name = "Drank water"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int"

[[metrics]]
    name = "Kept up Routine"
    color1 = "#83a598"
    color2 = "#abb31b"
    rule = "int10"
